version: "3"

services:
  nudatu_project:
    build: 
      context: .
    ports: 
      - "8000:8000"
    volumes: 
      - ./nudatu_project:/nudatu_project
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"