# Generated by Django 2.2.3 on 2019-07-15 19:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('movies_api', '0002_auto_20190715_1918'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='total_comments',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
