# Generated by Django 2.2.3 on 2019-07-16 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies_api', '0005_auto_20190716_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='total_comments',
            field=models.IntegerField(),
        ),
    ]
