# Generated by Django 2.2.3 on 2019-07-31 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies_api', '0006_auto_20190716_2042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='rank',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='total_comments',
        ),
        migrations.CreateModel(
            name='Top',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.CharField(max_length=1)),
                ('movie_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies_api.Movie')),
            ],
        ),
    ]
