# Generated by Django 2.2.3 on 2019-07-31 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies_api', '0007_auto_20190731_1559'),
    ]

    operations = [
        migrations.RenameField(
            model_name='top',
            old_name='movie_id',
            new_name='movie',
        ),
        migrations.RemoveField(
            model_name='top',
            name='rank',
        ),
    ]
