# Generated by Django 2.2.3 on 2019-07-31 14:19

import builtins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies_api', '0008_auto_20190731_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='genere',
            field=models.CharField(default=builtins.id, max_length=50),
            preserve_default=False,
        ),
    ]
